# Generated by Django 5.0.1 on 2024-01-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toolattachment',
            field=models.ForeignKey(blank=True, help_text="Select a tool's function to display in post_details.html", null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolattachment'),
        ),
    ]
