# Generated by Django 5.0.1 on 2024-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_toolattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
