# Generated by Django 5.0.1 on 2024-01-31 02:50

import blog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=160, verbose_name='intro'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.TextField(validators=[blog.models.validate_comma_separated_words], verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
    ]
