# Generated by Django 5.0.1 on 2024-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_managers_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='keywords',
            field=models.TextField(verbose_name='keywords'),
        ),
    ]
