# Generated by Django 6.0.9 on 2026-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posttranslation_keywords'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='posttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='blog_post_translation_uniq_lang'),
        ),
    ]
