# Generated by Django 5.0.1 on 2024-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattachment',
            name='function_name',
            field=models.CharField(blank=True, default=None, help_text="Unique identifier for the tool's function", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='toolattachment',
            name='template_name',
            field=models.CharField(blank=True, default=None, help_text="Template path for the tool's function", max_length=100, null=True),
        ),
    ]
