# Generated by Django 5.0.1 on 2024-02-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_toolattachment_function_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattachment',
            name='function_name',
            field=models.CharField(blank=True, default=None, help_text="Unique identifier for the tool's function", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='toolattachment',
            name='template_name',
            field=models.CharField(blank=True, default=None, help_text="Template path for the tool's function", max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ToolAttachmentTranslation',
        ),
    ]
