# Generated by Django 4.2.10 on 2024-03-04 20:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_convertedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattachment',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
