# Generated by Django 5.0.1 on 2024-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_toolattachment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_file', models.FileField(upload_to='merged_pdfs/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
