# Generated by Django 5.0.1 on 2024-03-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_mergedpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MergedPDF',
        ),
    ]
