# Generated by Django 5.2.9 on 2025-12-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_delete_mergedpdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertedPDF',
        ),
    ]
