# Generated by Django 5.2.9 on 2026-01-01 05:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_delete_convertedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattachment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
