# Generated by Django 5.2.9 on 2026-01-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_toolattachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolattachment',
            name='description',
        ),
    ]
